Store the monad that caused an UnwrapError
dry-rb/dry-monads pull request #138
Opened 2020-12-18 11:11 UTC by rewritten

Forcing the use of `yield` (which is in fact an implementation artifact) to write flowing method bodies is not always nice, because it requires a relatively high mental gymnastics.

With this change, we can have an alternative way that relies more on standard ruby constructs:

```rb
class SomeService
  # include Dry::Monads[:do] not needed anymore
  include Dry::Monads[:result]

  # Returns Failure(3.14)
  def call
    a = collaborator.call(**args).value!
    b = other_collaborator.call(**args).value!
 
    Success(a + b)
  rescue Dry::Monads::UnwrapError => exception
    exception.source
  end

  def collaborator
    ->(**) { Success(42) }
  end

  def other_collaborator
    ->(**) { Failure(3.14) }
  end
end
```

while with `do` it would be shorter but less ruby-like:

```rb
class SomeService
  include Dry::Monads[:do]
  include Dry::Monads[:result]

  # Returns Failure(3.14)
  def call
    a = yield collaborator.call(**args)
    b = yield other_collaborator.call(**args)
 
    Success(a + b)
  end

  def collaborator
    ->(**) { Success(42) }
  end

  def other_collaborator
    ->(**) { Failure(3.14) }
  end
end
```

2020-12-19 10:04 UTC, flash-gordon requested changes
> Forcing the use of yield (which is in fact an implementation artifact) to write flowing method bodies is not always nice, because it requires a relatively high mental gymnastics.
>
> With this change, we can have an alternative way that relies more on standard ruby constructs:

I disagree with this, but ofc it's up to the user whether to go for do notation or not. 
Note that you can use `bind` instead of `yield`:

```ruby
  def call
    a = bind collaborator.call(**args)
    b = bind other_collaborator.call(**args)
 
    Success(a + b)
  end
```

I'm not against adding `source` to the exception class but please make a little adjustment before I can merge it in.

2020-12-21 12:31 UTC, rewritten commented on lib/dry/monads/errors.rb
>          super("value! was called on #{ctx.inspect}")
Definitely! :)

2020-12-21 13:32 UTC, rewritten commented
Also, thanks to the pointer to the `bind` usage - it was not 100% clear from the documentation that it could be used that way, and the `do` integration specs do not show the usage.

2021-07-18 17:26 UTC, merged

2021-07-18 17:27 UTC, flash-gordon commented
I'll rename `source` to `receiver` to make it consistent with ruby's `NameError`